spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: sql-server
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: cherifayman4545@gmail.com
    password: gbkafmjwyjjtbrut
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
